### PR TITLE
Adds tooltip directive

### PR DESCRIPTION
**Pull request by shusain**

### CODE REVIEW

**Comment by hassanbazzi** [comment]
Does this detect if it's going offscreen and switch its alignment?

**Comment by shusain** [comment]
No as is this one was just to get the styling correct for the tooltip to match the styles on Quora and to fix the issues with the text going outside the tooltip container:
image

The drop downs issue was the one where it was supposed to automatically determine which direction to open.  It's definitely something we could possibly do with tooltips but really this was just for the sake of having control over the styling and retain the existing functionality (as well as making it easier for us to add more features like auto placement down the line).

**Comment by hassanbazzi** [comment]
Alright. Sounds good to me. Ready to be merged?

**Comment by shusain** [comment]
Yes I think so.

---

For drop downs I just have the basics started in a branch here to setup the new directive that iterates over a list but still need to incorporate some of this positioning code.

Instead of adding the elements as siblings of the element with the tooltip this is adding the elements to be the first elements in the body and then positioning them from there.  Reason for doing that was the absolutely positioned elements inherit their width from their parent so without setting an explicit width there was no way to get the tooltip to dynamically size to it's contents and/or allow us to specify a width.  Adding them to the body means they can be as wide as the body by default but we can set an explicit width and if none is set and the text is short enough the container just fits the text.

I think this is good to merge, the only thing with what I'm explaining above that can be an issue is controlling the stacking of the tooltips relative to things like the modal.  I'm just not fully aware of all the use cases right now or the exact implications of adding the tooltips to the body that way, z-index may still be enough to modify the stacking but that and any other special use cases will need to be tested in the app.

**Comment by hassanbazzi** [comment]
The main issue you run into is `overflow: hidden`

**Comment by shusain** [comment]
@hassanbazzi not sure what you're referencing there, `overflow:hidden` you mean on the body?

I added a gh-pages branch to this repo so github picks that up and deploys the static site to https://townsquared.github.io/utils and if you checkout that branch can easily test things out there.  I have the gh-pages checked out in it's own folder so then I'm just using `bower link` to link the branch I'm working on into the gh-pages to build and test things out.

**Comment by hassanbazzi** [comment]
I mean. Let's say you're inside a modal. The div of the modal is probably overflowed to hidden so things don't overflow out of it. Then if something goes out of the right, it'll be cut off for example

**Comment by shusain** [comment]
@hassanbazzi gotcha yeah following how that can be an issue.  I'm going to take the built version of this and drop it into the app for the sake of testing.  Right now the pivotal issue this is meant to fix (https://www.pivotaltracker.com/story/show/112077211) lists a few places to initially replace the tooltip none of which are in modals so not sure we really need to immediately address that.

In order to make this work in the utils and in the main app I added a html2js task to gulp that uses the ng-html2js plugin to add the templates to a JS file that uses the same module and uses the $templateCache to load up the HTML for the directive.

**Comment by shusain** [comment]
Just pushed a change to get the html2js conversion merged in with the existing build steps so it ends up in the bundled/minified JS file that the app loads.

**Comment by shusain** [comment]
@hassanbazzi think this is good to merge now.  The last commit was mostly just fixing up the gulp file to allow it to build the html2js and concat any css from the module so it can be loaded into the main-app.  I tested actually loading it into the main app by using symbolic links to link the /utils folder in place of the angular-ts-utils in the bower_components... long story short I was able to test that the files built here can be incorporated into the main-app and made the changes there locally to verify this all works fine.

**Comment by hassanbazzi** [comment]
LGTM

**Pull request merged**
